global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIA3HFOVU3KT3LBB7EP
        secret_key: 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
        port: 9100
