global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-west-2
        access_key:AKIA3HFOVU3KRCZ3PBMC
        secret_key: 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
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        regex: '(.*)' #default value
        target_label: _address_
        replacement: '${1}:9100'
        # action: keep
        # Use the instance ID as the instance label
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
