global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:

  - job_name: 'node_exporter'

    static_configs:

     - targets: ['172.31.30.76:9100']
     - targets: ['172.31.25.85:9100']
     - targets: ['172.31.23.172:9100']
      
