global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-west-2
        access_key: AKIAZI2LCICGMH6Y3QPI
        secret_key: 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
        port: 9100
