global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:

  - job_name: 'node_exporter'

    static_configs:

     - targets: ['172.31.28.69:9100']
     - targets: ['172.31.21.48:9100']
      
