global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.76.255:9090','172.31.46.157:9100','172.31.32.12:9100']
