global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:

  - job_name: 'node_exporter'

    static_configs:

      - targets: ['3.85.144.175:9100']
      - targets: ['3.90.240.30:9100']
      
